// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function DeleteManagedBind(arg1:string):Promise<domain.DashboardState>;

export function GetDashboard():Promise<domain.DashboardState>;

export function GetReloadSamples():Promise<Array<string>>;

export function GetStartupError():Promise<string>;

export function ListEmojiCatalog():Promise<domain.EmojiCatalog>;

export function ReloadFromDisk():Promise<domain.DashboardState>;

export function SetFavorite(arg1:string,arg2:boolean):Promise<domain.DashboardState>;

export function UpdateSettings(arg1:domain.UpdateSettingsRequest):Promise<domain.DashboardState>;

export function UpsertManagedBind(arg1:domain.UpsertBindRequest):Promise<domain.DashboardState>;
