// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteManagedBind(arg1) {
  return window['go']['main']['App']['DeleteManagedBind'](arg1);
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function GetReloadSamples() {
  return window['go']['main']['App']['GetReloadSamples']();
}

export function GetStartupError() {
  return window['go']['main']['App']['GetStartupError']();
}

export function ListEmojiCatalog() {
  return window['go']['main']['App']['ListEmojiCatalog']();
}

export function ReloadFromDisk() {
  return window['go']['main']['App']['ReloadFromDisk']();
}

export function SetFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetFavorite'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpsertManagedBind(arg1) {
  return window['go']['main']['App']['UpsertManagedBind'](arg1);
}
